using Microsoft.EntityFrameworkCore;
using WDAS.Application;
using WDAS.Domain;
using WDAS.Domain.Entities;
using WDAS.Domain.Enums;
using WDAS.Infrastructure.Persistence;

namespace WDAS.Infrastructure.Seeding;

public static class SecurityRolesBootstrap
{
    public static async Task EnsureSchemaAndSeedAsync(WdasDbContext db)
    {
        if (db.Database.IsRelational())
        {
            await EnsureTablesAsync(db);
            await MigrateLegacyRoleMappingsAsync(db);
        }

        await SeedSystemRolesAsync(db);
    }

    private static async Task EnsureTablesAsync(WdasDbContext db)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "SecurityRoles" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" character varying(120) NOT NULL,
                    "Code" character varying(64) NOT NULL,
                    "Description" character varying(1000),
                    "IsSystem" boolean NOT NULL,
                    "IsActive" boolean NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone,
                    CONSTRAINT "PK_SecurityRoles" PRIMARY KEY ("Id")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SecurityRoles_Code" ON "SecurityRoles" ("Code");

                CREATE TABLE IF NOT EXISTS "SecurityRolePermissions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "RoleId" integer NOT NULL,
                    "PermissionKey" character varying(120) NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone,
                    CONSTRAINT "PK_SecurityRolePermissions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_SecurityRolePermissions_SecurityRoles_RoleId"
                        FOREIGN KEY ("RoleId") REFERENCES "SecurityRoles" ("Id") ON DELETE CASCADE
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SecurityRolePermissions_RoleId_PermissionKey"
                    ON "SecurityRolePermissions" ("RoleId", "PermissionKey");
                """);
        }
        catch
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS SecurityRoles (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    Name TEXT NOT NULL,
                    Code TEXT NOT NULL,
                    Description TEXT,
                    IsSystem INTEGER NOT NULL,
                    IsActive INTEGER NOT NULL,
                    CreatedAtUtc TEXT NOT NULL,
                    UpdatedAtUtc TEXT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS IX_SecurityRoles_Code ON SecurityRoles (Code);

                CREATE TABLE IF NOT EXISTS SecurityRolePermissions (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    RoleId INTEGER NOT NULL,
                    PermissionKey TEXT NOT NULL,
                    CreatedAtUtc TEXT NOT NULL,
                    UpdatedAtUtc TEXT,
                    FOREIGN KEY (RoleId) REFERENCES SecurityRoles (Id) ON DELETE CASCADE
                );
                CREATE UNIQUE INDEX IF NOT EXISTS IX_SecurityRolePermissions_RoleId_PermissionKey
                    ON SecurityRolePermissions (RoleId, PermissionKey);
                """);
        }

        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "RoleMappings" ADD COLUMN IF NOT EXISTS "RoleId" integer;
                """);
        }
        catch
        {
            try
            {
                await db.Database.ExecuteSqlRawAsync("ALTER TABLE RoleMappings ADD COLUMN RoleId INTEGER");
            }
            catch
            {
                /* exists */
            }
        }
    }


    private static async Task MigrateLegacyRoleMappingsAsync(WdasDbContext db)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                UPDATE "RoleMappings" rm
                SET "RoleId" = sr."Id"
                FROM "SecurityRoles" sr
                WHERE rm."RoleId" IS NULL
                  AND rm."Role" IS NOT NULL
                  AND sr."Code" = CASE rm."Role"
                    WHEN 1 THEN 'SuperAdmin'
                    WHEN 2 THEN 'DepartmentAdmin'
                    WHEN 3 THEN 'MakerOwner'
                    WHEN 4 THEN 'Approver'
                    WHEN 5 THEN 'Auditor'
                    WHEN 6 THEN 'ItAdmin'
                    ELSE sr."Code"
                  END;
                """);
        }
        catch { /* legacy column may be gone */ }
    }
    public static async Task SeedSystemRolesAsync(WdasDbContext db)
    {
        var now = DateTime.UtcNow;
        var defs = new (string Name, string Code, string Description)[]
        {
            ("Super Admin", RoleNames.SuperAdmin, "Full system administrator with configuration access."),
            ("Super Admin (Configuration)", RoleNames.ConfigAdmin, "Configuration-only administrator. Predefined role — cannot be deleted."),
            ("Dept Admin", RoleNames.DepartmentAdmin, "Department-level oversight and reporting."),
            ("Maker", RoleNames.MakerOwner, "Creates and owns documents through the approval cycle."),
            ("Approver", RoleNames.Approver, "Reviews and acts on assigned approval steps."),
            ("Auditor", RoleNames.Auditor, "Read-only compliance and audit access."),
            ("IT Admin", RoleNames.ItAdmin, "Directory and user administration."),
        };

        foreach (var def in defs)
        {
            var role = await db.SecurityRoles.FirstOrDefaultAsync(r => r.Code == def.Code);
            if (role is null)
            {
                role = new SecurityRole
                {
                    Name = def.Name,
                    Code = def.Code,
                    Description = def.Description,
                    IsSystem = true,
                    IsActive = true,
                    CreatedAtUtc = now
                };
                db.SecurityRoles.Add(role);
                await db.SaveChangesAsync();
            }
            else
            {
                role.Name = def.Name;
                role.Description = def.Description;
                role.IsSystem = true;
                role.IsActive = true;
                role.UpdatedAtUtc = now;
                await db.SaveChangesAsync();
            }

            var desired = PermissionCatalog.ForLegacyRole(def.Code).ToHashSet(StringComparer.Ordinal);
            if (def.Code == RoleNames.SuperAdmin)
            {
                foreach (var key in PermissionCatalog.AllKeys)
                {
                    desired.Add(key);
                }
            }

            foreach (var key in desired)
            {
                var exists = await db.SecurityRolePermissions
                    .AnyAsync(p => p.RoleId == role.Id && p.PermissionKey == key);
                if (exists)
                {
                    continue;
                }

                db.SecurityRolePermissions.Add(new SecurityRolePermission
                {
                    RoleId = role.Id,
                    PermissionKey = key,
                    CreatedAtUtc = now
                });
            }

            await db.SaveChangesAsync();
        }

        if (!db.Database.IsRelational())
        {
            return;
        }

        try
        {
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "RoleMappings"
                    ADD CONSTRAINT "FK_RoleMappings_SecurityRoles_RoleId"
                    FOREIGN KEY ("RoleId") REFERENCES "SecurityRoles" ("Id") ON DELETE RESTRICT;
                """);
        }
        catch { /* already exists */ }
    }

    public static string RoleCodeForLegacy(ApplicationRole role) =>
        SecurityRoleIds.FromLegacyEnum((int)role);

    public static async Task<int> RoleIdForLegacyAsync(
        WdasDbContext db,
        ApplicationRole role,
        CancellationToken cancellationToken = default)
    {
        var code = RoleCodeForLegacy(role);
        if (string.IsNullOrWhiteSpace(code))
        {
            code = SecurityRoleIds.MakerOwner;
        }

        return await db.SecurityRoles
            .AsNoTracking()
            .Where(r => r.Code == code)
            .Select(r => r.Id)
            .FirstAsync(cancellationToken);
    }
}
