using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WDAS.Infrastructure.Migrations;

/// <inheritdoc />
public partial class AddDocumentRecordNumber : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<long>(
            name: "RecordNumber",
            table: "Documents",
            type: "bigint",
            nullable: false,
            defaultValue: 0L);

        migrationBuilder.Sql(
            """
            WITH numbered AS (
                SELECT "Id", ROW_NUMBER() OVER (ORDER BY "CreatedAtUtc", "Id") AS rn
                FROM "Documents"
            )
            UPDATE "Documents" AS d
            SET "RecordNumber" = n.rn
            FROM numbered AS n
            WHERE d."Id" = n."Id";
            """);

        migrationBuilder.Sql(
            """
            ALTER TABLE "Documents" ALTER COLUMN "RecordNumber" DROP DEFAULT;
            ALTER TABLE "Documents" ALTER COLUMN "RecordNumber" ADD GENERATED BY DEFAULT AS IDENTITY;
            """);

        migrationBuilder.Sql(
            """
            SELECT setval(
                pg_get_serial_sequence('"Documents"', 'RecordNumber'),
                COALESCE((SELECT MAX("RecordNumber") FROM "Documents"), 1));
            """);

        migrationBuilder.CreateIndex(
            name: "IX_Documents_RecordNumber",
            table: "Documents",
            column: "RecordNumber",
            unique: true);

        migrationBuilder.AddColumn<long>(
            name: "RecordNumber",
            table: "DocumentSearchIndexes",
            type: "bigint",
            nullable: false,
            defaultValue: 0L);

        migrationBuilder.Sql(
            """
            UPDATE "DocumentSearchIndexes" AS i
            SET "RecordNumber" = d."RecordNumber"
            FROM "Documents" AS d
            WHERE i."DocumentId" = d."Id";
            """);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropIndex(
            name: "IX_Documents_RecordNumber",
            table: "Documents");

        migrationBuilder.DropColumn(
            name: "RecordNumber",
            table: "DocumentSearchIndexes");

        migrationBuilder.DropColumn(
            name: "RecordNumber",
            table: "Documents");
    }
}
